/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

class IntegratironTest { 
    public static void main(String[] args) {
        System.out.println("Hello 112233");
    }
}
